# Generated by Django 4.2.7 on 2025-09-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfrm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
